export const UpdateType = {
    UPDATE_TITLE: "UPDATE_TITLE",
    UPDATE_DESC: "UPDATE_DESC",

    INSERT_FEATURE: "INSERT_FEATURE",
    UPDATE_FEATURE_PROPS: "UPDATE_FEATURE_PROPS",
    UPDATE_FEATURE_GEOMETRY: "UPDATE_FEATURE_GEOMETRY",
    DELETE_FEATURE: "DELETE_FEATURE",

    INSERT_TEXT_BOX: "INSERT_TEXT_BOX",
    UPDATE_TEXT_BOX: "UPDATE_TEXT_BOX",
    DELETE_TEXT_BOX: "DELETE_TEXT_BOX",
};
