name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm install
        working-directory: server
      - run: npm install
        working-directory: client
      - run: npm run build --if-present
        working-directory: client
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'mapology-1'
          heroku_email: 'nguzzardo3@gmail.com'
          appdir: "server"
