name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  component-tests:
    name: Component Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1
        with:
          working-directory: client
          component: true
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1
        with:
          working-directory: client
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
    
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install server npm modules
        run: npm install
        working-directory: server
      - name: Install client npm modules
        run: npm install
        working-directory: client
      - name: Backend tests
        run: npm run test
        working-directory: server

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install server npm modules
        run: npm install
        working-directory: server
      - name: Install client npm modules
        run: npm install
        working-directory: client
      - name: Build react project
        run: npm run build --if-present
        working-directory: client
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'mapology-1'
          heroku_email: 'nguzzardo3@gmail.com'
          appdir: "server"
